CREATE TABLE IF NOT EXISTS lesson (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    start_time timestamp NOT NULL,
    zoom_link VARCHAR (255),
    address VARCHAR (255),
    logoped_id INT NOT NULL,
    user_id INT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (logoped_id) REFERENCES logoped(id),
    FOREIGN KEY (user_id) REFERENCES users(id));