CREATE TABLE IF NOT EXISTS user_role (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    role_name VARCHAR (255),
    PRIMARY KEY (id));

INSERT INTO user_role (role_name)
VALUES (
           'ROLE_USER'
       ),
       (
           'ROLE_LOGOPED'
       ),
       (
           'ROLE_ADMIN'
       );