CREATE TABLE IF NOT EXISTS users (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR (255),
    last_name VARCHAR (255),
    email VARCHAR (255) UNIQUE,
    phone_number VARCHAR (255) UNIQUE,
    password VARCHAR (255),
    user_status VARCHAR (255),
    PRIMARY KEY (id));


INSERT INTO users (first_name, last_name, email, phone_number, password, user_status)
VALUES (
        'Юрий',
        'Мусиенко',
        '97musienko@gmail.com',
        '+375298344491',
        '$2y$12$QKQ2d03.6SCPEQhLlaZusOJT9Q/ODqnvFHT6JCdpqvxKeXHa7KviG',
        'ACTIVE'
       );