CREATE TABLE IF NOT EXISTS activate_key(
    id INT GENERATED BY DEFAULT AS IDENTITY,
    simple_key VARCHAR (15) NOT NULL UNIQUE,
    user_id INT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id)
       REFERENCES users (id));