CREATE TABLE IF NOT EXISTS category (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    category_name VARCHAR (255) NOT NULL UNIQUE,
    PRIMARY KEY (id));

INSERT INTO category (category_name)
VALUES (
           'Логопед'
       ),
       (
           'Подготовка к школе'
       );