CREATE TABLE IF NOT EXISTS form (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    logoped_id INT NOT NULL,
    phone_number VARCHAR (255),
    description VARCHAR (255),
    PRIMARY KEY (id),
    foreign key (logoped_id) references logoped(id));