CREATE TABLE IF NOT EXISTS logoped_client (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    user_id INT NOT NULL,
    logoped_id INT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (logoped_id) REFERENCES logoped(id));