CREATE TABLE IF NOT EXISTS user_role (
                                         id INT GENERATED BY DEFAULT AS IDENTITY,
                                         role_name VARCHAR (255),
                                         PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS users (
                                     id INT GENERATED BY DEFAULT AS IDENTITY,
                                     first_name VARCHAR (255),
                                     last_name VARCHAR (255),
                                     email VARCHAR (255) UNIQUE,
                                     phone_number VARCHAR (255) UNIQUE,
                                     password VARCHAR (255),
                                     user_status VARCHAR (255),
                                     PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS users_user_role (
                                               user_id int8 NOT NULL ,
                                               user_role_id int8 not null,
                                               foreign key (user_role_id) references user_role(id),
                                               foreign key (user_id) references users(id));
CREATE TABLE IF NOT EXISTS activate_key(
                                           id INT GENERATED BY DEFAULT AS IDENTITY,
                                           simple_key VARCHAR (15) NOT NULL UNIQUE,
                                           user_id INT NOT NULL,
                                           PRIMARY KEY (id),
                                           FOREIGN KEY (user_id)
                                               REFERENCES users (id));
CREATE TABLE IF NOT EXISTS category (
                                        id INT GENERATED BY DEFAULT AS IDENTITY,
                                        category_name VARCHAR (255),
                                        PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS logoped (
                                       id INT GENERATED BY DEFAULT AS IDENTITY,
                                       user_id INT NOT NULL,
                                       education VARCHAR (255),
                                       work_place VARCHAR (255),
                                       work_experience INT,
                                       PRIMARY KEY (id),
                                       foreign key (user_id) references users(id));

CREATE TABLE IF NOT EXISTS logoped_category (
                                                logoped_id INT NOT NULL ,
                                                category_id INT not null,
                                                foreign key (logoped_id) references logoped(id),
                                                foreign key (category_id) references category(id));
CREATE TABLE IF NOT EXISTS form (
                                    id INT GENERATED BY DEFAULT AS IDENTITY,
                                    logoped_id INT NOT NULL,
                                    phone_number VARCHAR (255),
                                    description VARCHAR (255),
                                    PRIMARY KEY (id),
                                    foreign key (logoped_id) references logoped(id));